### ISSUE TITLE
self.status attribute in Class Controller

### ISSUE THREAD

**Issue by konstantinos-papadopoulos** [intracom-telecom-sdn/nstat#105]
While adding the new getcontroller() method I checked that the ```self.status``` is defined within the Controller constructor and
- set within wrapper method cleanup()
- set within wrapper method restart()
- set within wrapper method start()
- set within wrapper method stop()

Where is the ```self.status``` read. Should we remove it from everywhere? What is the meaning of setting/maintaining this attribute?

**Comment by tomsou** [comment]
This is a placeholder, imported in the frame of refactoring for every new class (controller, emulator, nb-generator). The idea is to keep the object status within a method running. 
In fact it turned out that there is no added value from this. 
It is currently unused, so we could get rid off it.

**Comment by konstantinos-papadopoulos** [comment]
Thanks Thomas. See commit id 2d56e67
