### ISSUE TITLE
Remote branch v1.0 not found in upstream origin

### ISSUE THREAD

**Issue by kerwin-chinea** [intracom-telecom-sdn/nstat#107]
Hi, 
I think there should by an error on your installation recipe.
Step 1
`git clone --branch v1.0 https://github.com/intracom-telecom-sdn/nstat-cperf.git nstat-cperf.`

This is the output I get when doing it:
```
Cloning into 'nstat-cperf'...
fatal: Remote branch v1.0 not found in upstream origin.
```

Let me know if I am wrong.

Thanks a lot.

**Comment by konstantinos-papadopoulos** [comment]
Hello @kerwin-chinea and thank you for your input.
It should now be ok. Please find under [ntracom-telecom-sdn/nstat-cperf](https://github.com/intracom-telecom-sdn/nstat-cperf#nstat-automated-stress-tests-for-opfnvcperf-project) the updated README regarding the NSTAT: Automated stress tests for OPFNV/CPerf project.
  -  Your feedback is more than welcome.
  -  We expect your new issues to be opened under the [nstat-cperf](https://github.com/intracom-telecom-sdn/nstat-cperf/issues) issues section.

Br
The NSTAT team
