### ISSUE TITLE
Vagrantfile multiple VMs

### ISSUE THREAD

**Issue by konstantinos-papadopoulos** [intracom-telecom-sdn/nstat#5]
At the moment each NSTAT node is deployed by a separate ```Vagrantfile``` each one located under ```$NSTAT_SRC/vagrant``` folder. Since every Vagrantfile creates a separate Host-only network, NSTAT nodes when deployed belong to different Host-only networks and therefore ssh communication between them is not feasible.

The issue has been verified for provider: virtualbox. It might apply for provider: libvirt as well.

**Solution**: Use of one Vagrantfile ie. packaged_multi to deploy all necessary NSTAT nodes, so that all of them belong o the same Host-only network. @panageo , @anastop

**Comment by panageo** [comment]
New implementation of vagrant files has been made. The issue is fixed.
